name: Unittest

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"
      - name: Install dependencies
        env:
          SKIP_GITHOOKS: true
        run: |
          source setup_venv.sh
      - name: Run unittests
        run: |
          source .venv/bin/activate
          ./run_tests.sh
      - name: Export Coverage report
        uses: actions/upload-artifact@v4
        with:
          name: Rankings
          path: htmlcov/index.html
